# DICCIONARIO CON COLUMNAS y DATOS DE LA BDD

In [3]:
import psycopg2

localhost = 'localhost'
#data_base = 'postgres'
data_base = 'TRABAJO_DE_TITULO'
user_1 = 'postgres'
pass_word = 'admin'

In [4]:
conexion = psycopg2.connect(host=localhost, database=data_base, user= user_1, password=pass_word, port = 5433)
cur = conexion.cursor()

In [5]:
DICC_BDD = {}
DICC_BDD.setdefault('ID',[])
DICC_BDD.setdefault('COLUMNAS',[])
DICC_BDD.setdefault('TYPES',[])

[]

In [6]:
cur.execute('SELECT "ID", "NOM_COL", "TIPO_DATO" FROM pruebas."DICCIONARIO_DE_DATOS";')

In [8]:
for i in cur.fetchall():
    print(i[0]," - ",i[1]," - ",i[2])
    DICC_BDD["ID"].append(i[0])
    DICC_BDD["COLUMNAS"].append(i[1])
    DICC_BDD["TYPES"].append(i[2])

3  -  hotel  -  object
4  -  is_canceled  -  int64
5  -  lead_time  -  int64
6  -  arrival_date_year  -  int64
7  -  arrival_date_month  -  object
8  -  arrival_date_week_number  -  int64
9  -  arrival_date_day_of_month  -  int64
10  -  stays_in_weekend_nights  -  int64
11  -  stays_in_week_nights  -  int64
12  -  adults  -  int64
13  -  children  -  float64
14  -  babies  -  int64
15  -  meal  -  object
16  -  country  -  object
17  -  market_segment  -  object
18  -  distribution_channel  -  object
19  -  is_repeated_guest  -  int64
20  -  previous_cancellations  -  int64
21  -  previous_bookings_not_canceled  -  int64
22  -  reserved_room_type  -  object
23  -  assigned_room_type  -  object
24  -  booking_changes  -  int64
25  -  deposit_type  -  object
26  -  agent  -  float64
27  -  company  -  float64
28  -  days_in_waiting_list  -  int64
29  -  customer_type  -  object
30  -  adr  -  float64
31  -  required_car_parking_spaces  -  int64
32  -  total_of_special_requests  -  int64
33  -  reservation_status  -  object
34  -  reservation_status_date  -  object

# DICCIONARIO CON DATOS SOBRE LAS COLUMNAS DE ENTRADA

In [7]:
import pandas as pd
import os

In [8]:
def det_extension_file(archivo):
    name_file, extension_file = os.path.splitext(archivo)
    return name_file, extension_file

In [9]:
archivo = "hotel_bookings_1.csv"
var1, var2 = det_extension_file(archivo)
var1, var2

('hotel_bookings_1', '.csv')

In [10]:
def dataframe_from_file(archivo):
    aux1 , aux2 = os.path.splitext(archivo)
    if (aux2) == '.csv':
        dataframe = pd.read_csv(archivo)
    if (aux2) == '.xlsx':
        dataframe = pd.read_excel(archivo)
    return dataframe

In [11]:
df = dataframe_from_file(archivo)
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [12]:
def dframe_to_dicc(dataframe):
    dic = {}
    dic.setdefault('COLUMNAS',[])
    dic.setdefault('TYPES',[])
    for i in range(len(df.columns)):
        dic['COLUMNAS'].append(df.columns[i])
        dic['TYPES'].append(df[dic['COLUMNAS'][i]].dtype.name)
    return dic

In [13]:
#DICCIONARIO DE VARIABLES DEL DATAFRAME
DICC_DF = dframe_to_dicc(df)
DICC_DF

{'COLUMNAS': ['hotel',
  'is_canceled',
  'lead_time',
  'arrival_date_year',
  'arrival_date_month',
  'arrival_date_week_number',
  'arrival_date_day_of_month',
  'stays_in_weekend_nights',
  'stays_in_week_nights',
  'adults',
  'children',
  'babies',
  'meal',
  'country',
  'market_segment',
  'distribution_channel',
  'is_repeated_guest',
  'previous_cancellations',
  'previous_bookings_not_canceled',
  'reserved_room_type',
  'assigned_room_type',
  'booking_changes',
  'deposit_type',
  'agent',
  'company',
  'days_in_waiting_list',
  'customer_type',
  'adr',
  'required_car_parking_spaces',
  'total_of_special_requests',
  'reservation_status',
  'reservation_status_date'],
 'TYPES': ['object',
  'int64',
  'int64',
  'int64',
  'object',
  'int64',
  'int64',
  'int64',
  'int64',
  'int64',
  'float64',
  'int64',
  'object',
  'object',
  'object',
  'object',
  'int64',
  'int64',
  'int64',
  'object',
  'object',
  'int64',
  'object',
  'float64',
  'float64',
  'int64',
  'object',
  'float64',
  'int64',
  'int64',
  'object',
  'object']}